### ISSUE TITLE
In CLI tools section

### ISSUE THREAD

**Issue by DamienGS** [thelia/memo-book#1]
Last line of the table (Thelia:update) : update Thelia database. Before [doing] that you have to update Thelia files

**Comment by DamienGS** [comment]
In introduction line : "Thelia has a command line tools that can help you [ ] automate repetitive task[s] "

**Comment by DamienGS** [comment]
In the Description column you should decide if you want Capital letters or not at the beginning of each sentence.

**Comment by lunika** [comment]
Thanks.

If you want to see what I wrote if a more confortable way you can go here : http://thelia.github.io/memo-book/
